### ISSUE TITLE
Unable to run test and app

### ISSUE THREAD

**Issue by ericsiber** [SalahMswi/FizzBuzzTest#1]
After having installed (npm install), when running : 

npm test : 

> > fizzbuzz@1.0.0 test /Users/esiber/Downloads/FizzBuzzTest-master
> > jasmine-node spec/
> 
> sh: jasmine-node: command not found
> npm ERR! Test failed.

npm start : 

> > fizzbuzz@1.0.0 start /Users/esiber/Downloads/FizzBuzzTest-master
> > node main.js
> 
> module.js:442
>     throw err;
>     ^
> 
> Error: Cannot find module '../src/lib/fizzbuzz'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/esiber/Downloads/FizzBuzzTest-master/main.js:1:78)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
> 
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! fizzbuzz@1.0.0 start: `node main.js`
> npm ERR! Exit status 1

**Comment by SalahMswi** [comment]
Bonjour,

Sorry my mistake was that I didn't save jasmine-node as dependencie.

1)if you want to use jasmine-node :you have to do: npm install -g jasmine-node.

2) but what you should do is:

-install node (if you haven't).

-npm install

after that you can put :

-npm test

or npm start

Best regards

---

De : Eric Siber notifications@github.com
Envoyé : lundi 15 août 2016 22:10:13
À : SalahMswi/FizzBuzzTest
Objet : [SalahMswi/FizzBuzzTest] Unable to run test and app (#1)

After having installed (npm install), when running :

npm test :

fizzbuzz@1.0.0 test /Users/esiber/Downloads/FizzBuzzTest-master
jasmine-node spec/

sh: jasmine-node: command not found
npm ERR! Test failed.

npm start :

fizzbuzz@1.0.0 start /Users/esiber/Downloads/FizzBuzzTest-master
node main.js

module.js:442
throw err;
^

Error: Cannot find module '../src/lib/fizzbuzz'
at Function.Module._resolveFilename (module.js:440:15)
at Function.Module._load (module.js:388:25)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at Object. (/Users/esiber/Downloads/FizzBuzzTest-master/main.js:1:78)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! fizzbuzz@1.0.0 start: node main.js
npm ERR! Exit status 1

##

**Comment by ericsiber** [comment]
npm test works, but there is still an issue with npm start : 

> > fizzbuzz@1.0.0 start /Users/esiber/Downloads/FizzBuzzTest-master
> > node main.js
> 
> module.js:442
>     throw err;
>     ^
> 
> Error: Cannot find module '../src/lib/fizzbuzz'
>     at Function.Module._resolveFilename (module.js:440:15)
>     at Function.Module._load (module.js:388:25)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/Users/esiber/Downloads/FizzBuzzTest-master/main.js:1:78)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
> 
> npm ERR! Darwin 15.6.0
> npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v6.3.1
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! fizzbuzz@1.0.0 start: `node main.js`
> npm ERR! Exit status 1

**Comment by SalahMswi** [comment]
Bonjour,

Tu passe au repertoire src et làbas tu lance npm start.

J'attend ton retour si cela marche.

Cordialement

---

De : Eric Siber notifications@github.com
Envoyé : mardi 16 août 2016 13:52:37
À : SalahMswi/FizzBuzzTest
Cc : Salah Al Moussawi; Comment
Objet : Re: [SalahMswi/FizzBuzzTest] Unable to run test and app (#1)

npm test works, but there is still an issue with npm start :

fizzbuzz@1.0.0 start /Users/esiber/Downloads/FizzBuzzTest-master
node main.js

module.js:442
throw err;
^

Error: Cannot find module '../src/lib/fizzbuzz'
at Function.Module._resolveFilename (module.js:440:15)
at Function.Module._load (module.js:388:25)
at Module.require (module.js:468:17)
at require (internal/module.js:20:19)
at Object. (/Users/esiber/Downloads/FizzBuzzTest-master/main.js:1:78)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! fizzbuzz@1.0.0 start: node main.js
npm ERR! Exit status 1

##

**Comment by ericsiber** [comment]
Il n'y a aucun répertoire src

**Comment by SalahMswi** [comment]
j'ai fait un push

**Comment by ericsiber** [comment]
Issue closed as latest version can now be launched through "node start"
