### ISSUE TITLE
Demo App does not ask for optional parameters

### ISSUE THREAD

**Issue by ericsiber** [SalahMswi/FizzBuzzTest#2]
User of the v3 demo app would expect to be able to provide the parameters, but the demo app is running v1, v2, v3 with default, v3 with (2 ; 5) as parameters wheres we only expect to run v3 with optional parameters.

**Comment by SalahMswi** [comment]
du coup, il marche chez toi maintenant?

**Comment by SalahMswi** [comment]
You can now enter 2 parameters , and it will display the results (just for the version3 and of course it will return the same results of the versrion2 if you pass 3 and 5 as parameters).
I'm always ready for any modification.
Best regards.
